
name: Terraform Automation

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Terraform Init
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform init

      - name: Terraform Apply - Development
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          mkdir ~/.ssh
          echo ${{ secrets.SSH_KEY }} > ~/.ssh/tf-test.pub
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform workspace select eu-central-1.dev
          terraform apply -var-file region.eu-central-1.dev.tfvars -auto-approve
          
      - name: Terraform Apply - Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          mkdir ~/.ssh
          echo ${{ secrets.SSH_KEY }} > ~/.ssh/tf-test.pub
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform workspace select eu-west-1.dev
          terraform apply -var-file region.eu-west-1.dev.tfvars -auto-approve
          
